version: '3.8' #Versión del formato de docker compose

services:
  # Configuracion del contenedor Mysql
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: base_datos_prueba
      MYSQL_USER: user
      MYSQL_PASSWORD: poli_2424
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Configuracion del Contenedor PHP
  php:
    build:
      context: .
      dockerfile: DockerfilePhp
    container_name: php_container
    ports:
      - "8080:80"
    volumes:
      - ./volumen-php:/var/www/html
    depends_on:
      - db

# Volúmenes
volumes:
  db_data:
